name: taming-env
channels:
  - pytorch
  - nvidia                    # uncomment for gpu installation
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
#  - pytorch=2.1
  - pytorch-cuda=12.1         # specify your CUDA version
  - lightning=2.0
  - pytorch-lightning=2.0
  - torchmetrics=0.11
#  - pyg=2.4
#  - pytorch-scatter
#  - pytorch-sparse
  - pip
  - pip:
      - neptune-client==1.8.3
      - tensorboard
      - torch_spatiotemporal[experiment]==0.9.4